FROM debian:jessie

RUN apt-get update && apt-get install -y \
      build-essential git cmake sudo vim \
      swig usbutils bison flex python-dev \
      autoconf libtool pkg-config libssl-dev \
      xfce4 xfce4-goodies tightvncserver \
      net-tools

# gnuradio build deps
RUN apt-get install -y git-core cmake g++ python-dev \
  swig pkg-config libfftw3-dev libboost1.55-all-dev libcppunit-dev libgsl0-dev \
  libusb-dev libsdl1.2-dev python-numpy \
  python-cheetah python-lxml doxygen libxi-dev python-sip \
  libqt4-opengl-dev libqwt-dev libfontconfig1-dev libxrender-dev \
  python-sip python-sip-dev

ENV PYTHONPATH=/usr/lib/python2.7/site-packages/
#hack:uhd-host installation fail inside docker otherwise
RUN echo "" > /sbin/sysctl

RUN apt-get install -y osmo-sdr gr-osmosdr

# install thrift for gnuradio profiling
RUN cd /opt && git clone -b 0.9.2 --depth=1 \
  https://git-wip-us.apache.org/repos/asf/thrift.git thrift \
  && cd thrift && ./bootstrap.sh \
  && ./configure --disable-tests --with-lua=no --disable-tutorial \
  --with-perl=no && make -j 4 && make install && rm -rf /opt/thrift

#build gnuradio
RUN cd /opt && git clone --depth=1 -b v3.7.11 \
  https://github.com/gnuradio/gnuradio.git && cd gnuradio && \
  git submodule update --init && mkdir build && \
  cd build && cmake .. && make -j 4 && make install && rm -rf \
  /opt/gnuradio

RUN git clone https://github.com/Blockstream/satellite.git /opt/satellite

RUN cd /opt/satellite && ./install_gr_framers.sh && ./install_mods.sh \
  && ldconfig

EXPOSE 9090
COPY config.conf /root/.gnuradio/config.conf
COPY entrypoint.sh /
COPY vncserver.sh /
ENTRYPOINT ["/entrypoint.sh"]
