version: '2'
services:
  satellite:
    image: "aospan/bitcoin-satellite-profile"
    privileged: true
    environment:
        - FREQ=1578500000
        - GUI=1
        - VNCPASSWORD=secret
        - GAIN=10
        - VOLK_CONFIG=volk_config-intel-joule-570x
    ports:
        - 5901:5901
    volumes:
      - asset-volume:/tmp
  bitcoinfibre:
      image: "aospan/bitcoinfibre"
      volumes:
        - /mnt/hdd/bitcoin:/opt/bitcoin
        - asset-volume:/tmp

volumes:
  asset-volume:
