name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py_version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.py_version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov yapf isort shtab setuptools pytest-qt pytest-xvfb
        sudo apt update -y && sudo apt install -y xvfb libqt5gui5 libxcb-cursor0
        make && make install
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Check formatting
      run: |
        yapf --diff --recursive --verbose blocksatcli/ blocksatgui/
    - name: Check import sorting
      run: |
        isort --check-only blocksatcli/ blocksatgui/
    - name: Test with pytest
      run: |
        python -m pytest --cov=blocksatcli --cov=blocksatgui
    - name: Check launching and imports
      run: blocksat-cli --version
    - name: Check bash completion file is up to date
      run: |
        make completion
        git diff --exit-code blocksat-cli.bash-completion
