name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov yapf shtab
        make && make install
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Check formatting
      run: |
        yapf --diff --recursive --verbose blocksatcli/
    - name: Test with pytest
      run: |
        python -m pytest --cov=blocksatcli
    - name: Check launching and imports
      run: blocksat-cli --version
    - name: Check bash completion file is up to date
      run: |
        make completion
        git diff --exit-code blocksat-cli.bash-completion
